# Site settings
title: Blend IT Software, App & Web Development + Web Design
description:  Tried and tested Filipino talent. European service standards. Amazing prices and delivery times.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Blend IT
user_title: Software, App & Web Development + Web Design
user_description: Tried and tested Filipino talent. European service standards. Amazing prices and delivery times.
email: tonis@blendit.eu
twitter_username: ""
github_username:  ""
gplus_username:  ""
about_us_text: Blend IT brings you high quality software development and web design services by experienced young professional developers from Philippines with unbeatable pricing and with highly personal touch under the personal guidance of a successful European web projects manager!

# Google-analytics
google-analytics:
  id: UA-113289281-1

exclude: ['package.json', 'src', 'node_modules']


team:
  - name: Jay Paul Aying
    linkedin: https://www.linkedin.com/in/jaypaulaying/
    title: Co-Founder
    image: jay.png
    description: Software/Hardware Developer offering knowledge on software development using MVC, Agile principles, version control, as well as experience with Data Management.
    portfolios:
      - icon: makeuptransformation.png
        title: Make-up Transformation
        link: https://play.google.com/store/apps/details?id=com.tirserv.makeuptransformation&hl=en
      - icon: fml.png
        title: FML Moment
        link: https://play.google.com/store/apps/details?id=tirserv.com.fml_moment&hl=en
      - icon: sproutbooth.png
        title: SproutBooth
        link: https://play.google.com/store/apps/details?id=com.tirserv.sprout_booth&hl=en
      - icon: taoapp.png
        title: Tao Philippines Mobile App
        link: https://play.google.com/store/apps/details?id=com.taokalahi&hl=en
      - icon: taotech.png
        title: Tao Philippines Web App
        link: https://taotechph.com
      - icon: bagollabs.png
        title: Bagol Lab
        link: http://bagollabs.com
      - icon: credicompadre.png
        title: CrediCompadre
        link: https://www.credicompadre.mx
      - icon: boholwhitehouse.png
        title: Bohol White House
        link: http://www.boholwhitehouse.com
      - icon: nstransport.png
        title: Noel Silver Transport
        link: http://www.boholnstransport.com
      - icon: boholpaddlers.jpg
        title: Bohol Paddlers
        link: http://boholpaddlers.org
      - icon: wholesalecarpets.png
        title: Wholesale Carpets
        link: https://wholesalecarpets.co.uk
  - name: Reylieto Doblas
    linkedin: https://www.linkedin.com/in/reylieto-doblas-45052067/
    title: oftware Developer
    image: rey.png
    description: Having industry experience of 7 years. Involved in complex systems, data visualization and automation. 
    portfolios:
      - icon: tralopia.png
        title: Tralopia
        link: https://www.tralopia.com
      - icon: glimmer.png
        title: BI Glimmer
        link: https://drive.google.com/open?id=1SfJ1s1QhX_sJFHU5QP4ZGvbvOnDl7qc7
      - icon: listbroking.jpeg
        title: List Brooking
        link: https://drive.google.com/open?id=1Ir5vYukw6DckhkpjrBXUAlO2-f-uVZti
      - icon: phino.jpeg
        title: Phino
        link: https://drive.google.com/open?id=1QiYGFsnxOf-K9r_dcP9vAjd3IASFeXKe
      - icon: rapido.jpeg
        title: Rapido
        link: https://drive.google.com/open?id=1adeJPzn-qIeJVgiI_fcXGo7JYrbNqsdZ
      - icon: softonfire.jpeg
        title: Soft on Fire
        link: https://drive.google.com/open?id=1DGcn7G_tp31U4Rqx6EUrTC1uc7YYn6yV
      - icon: paymentprocessor.jpeg
        title: Payment Processor
        link: https://drive.google.com/open?id=1Exiu9MghGwtU9XCbHnasKViy4lQ6oeRe
      - icon: football.jpeg
        title: Football Prediction
        link: https://drive.google.com/open?id=1mIhIB8Kgtm5FM5xpkCgc5WiU3oiIAFM5
  - name: Jason Tiro
    linkedin: https://www.linkedin.com/in/jason-tiro-14a28488/
    title: Software Developer
    image: jason.png
    portfolios:
      - icon: boholinfo.png
        title: Bohol Info
        link: https://play.google.com/store/apps/details?id=bohol.info&hl=en
      - icon: beefarm.png
        title: Bohol Bee Farm
        link: https://www.boholbeefarm.com
      - icon: hayahay.png
        title: Hayahay
        link: http://www.hayahayresort.com
      - icon: casilan.png
        title: Casilan
        link: http://casilanrealty.com
      - icon: moonfools.png
        title: Moon Fools
        link: http://www.moonfools.com/
      - icon: greendesigns.png
        title: Green Design
        link: http://www.greendesignsbohol.com
      - icon: bohollocaldev.png
        title: Local Development Foundation
        link: http://www.localdevfoundation.com
      - icon: freedev.png
        title: Free Dev
        link: http://freedevbohol.com
      - icon: midpoint.png
        title: Midpoint
        link: http://www.midpointresidences.com
    description: Having industry experience of 3 years. Doing designing, mobile development, wordpress deployment, management and modification.
  - name: Joseph Mangmang
    linkedin: https://www.linkedin.com/in/joseph-mangmang/
    title: Software Developer
    image: joseph.png
    portfolios:
      - icon: pretextsms.png
        title: Pretext
        link: https://play.google.com/store/apps/details?id=org.nanoidea.pretextsms.mms
      - icon: persontracker.jpeg
        title: Person Tracker Live Prank
        link: https://play.google.com/store/apps/details?id=com.skimfix.personlocatorlive
      - icon: naks.jpeg
        title: Pretext
        link: https://play.google.com/store/apps/details?id=com.nanoidea.naksradio
      - icon: flyon.jpeg
        title: Fly On
        link: https://play.google.com/store/apps/details?id=com.nanoidea.JumpingBall
      - icon: freetext.jpeg
        title: PH Free Text
        link: https://play.google.com/store/apps/details?id=com.nanoidea.phfreetxt
    description: Self-taught developer. Started coding since middle high school. Doing designing, front-end, back-end, marketing and supports.
  - name: Charles Migriño
    linkedin: https://www.linkedin.com/in/charles-migrino
    title: Software Developer
    image: charles.png
    portfolios:
      - icon: ipos.jpeg
        title: iPOS
        link: https://docs.google.com/document/d/1m4vuHi2b-KXXzpCCpI0kbmJnR4ljKOS3m5yVtofAqlk/edit?usp=sharing
      - icon: yieldhub.png
        title: Yield Hub
        link: https://docs.google.com/document/d/1m4vuHi2b-KXXzpCCpI0kbmJnR4ljKOS3m5yVtofAqlk/edit?usp=sharing
      - icon: cloudpos.png
        title: CloudPOS
        link: https://docs.google.com/document/d/1m4vuHi2b-KXXzpCCpI0kbmJnR4ljKOS3m5yVtofAqlk/edit?usp=sharing
    description:  Passionate with programming. Self-taught developer and started engaging in software development in highschool. Creating beautiful and functional desktop, mobile, and web applications.
  - name: Cifergenno Salinas
    linkedin: https://www.linkedin.com/in/cifergenno-salinas
    title: Software Developer
    image: cifer.png
    description: Experienced Software Engineer. Skilled in VBA, PHP, CSS, HTML, Javascript, jQuery, Mootools, AngularJs, Ruby and Java.
    portfolios:
      - icon: nexusnet.png
        title: Nexus-net
        link: https://nexus-net.info
      - icon: r4apps.png
        title: R4Apps
        link: https://www.r4apps.com/en
  - name: Ryan Baldisco
    linkedin: https://www.linkedin.com/in/cifergenno-salinas
    title: Software Developer
    image: ryan.jpeg
    description: 
    portfolios:
      - icon: yieldhub.png
        title: yeildHUB
        link: https://drive.google.com/file/d/1XMRau2Gf1-hr_esF58ICFxMUjNyt0uMH/view?ts=5ac6290b
  - name: Reden John Zarra
    linkedin: https://www.linkedin.com/in/redjohnzarra/
    title: Software Developer
    image: reden.jpeg
    description: Has exceptional analytical and problem-solving skills and can work under pressure. Have high interest in trying new things. Trained to work in fast-paced environment. Experienced in collaborating and working with multiple teams, but capable working independently. Have an immense passion for my work.
    portfolios:
      - icon: glimmer.png
        title: Glimmer
        link: https://drive.google.com/file/d/11SxWSC4-lQFLErBVAQDDexGPtCKn3rG3/view
      - icon: mdiscount.png
        title: Member’s Discount
        link: https://drive.google.com/open?id=17nTcypGrRvsJTMxvm-jgeoshuL8Zj_Ee
      - icon: clination.png
        title: CLInation
        link: https://drive.google.com/open?id=1Gb-YUaXEn6r_rqNl9DJ2iiMNVDT-Rv7L
      - icon: hisd3.png
        title: HISD3
        link: https://drive.google.com/open?id=1T83KKVQUHFK2Pemm98BzukanxcrkhO2b
      - icon: isite.png
        title: iSite Solution
        link: https://drive.google.com/open?id=1IKRRKOD8YJD11oEFrhuUlyy3zxEO1NV9
     


form:
  description: (project details, how many pages, features, colors, reference site, current website, etc.)

team_image: blendit_team.jpeg


testimonials:
  - content: "I keep hearing from Estonian tech ventures about excellent quality and price ratio of developers in Philippines and Indonesia."
    name: Sven Illing, early stage investor
  